# Generated by Django 4.2.25 on 2025-11-14 11:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the book title (2-200 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Title must be at least 2 characters long.'), django.core.validators.MaxLengthValidator(200, 'Title cannot exceed 200 characters.')])),
                ('author', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Author name must be at least 2 characters long.'), django.core.validators.MaxLengthValidator(100, 'Author name cannot exceed 100 characters.')])),
                ('description', models.TextField(blank=True, help_text='Brief description of the book (max 1000 characters)', max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('published_date', models.DateField()),
                ('isbn', models.CharField(help_text='International Standard Book Number', max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_manage_books', 'Can create, update, and delete books')],
            },
        ),
    ]
